project:
  type: website
  output-dir: docs

website:
  title: "Timothy Abramov"
  navbar:
    left:
      - text: Feed
        href: index.qmd
      - text: Poems
        href: poems.qmd
      - text: Projects
        href: projects.qmd
      - text: About  
        href: about.qmd
  open-graph: true
  favicon: logo.png

format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: visual

