project:
  type: website
  output-dir: docs

website:
  title: "TimothyAbramov.github.io"
  navbar:
    left:
      - text: Feed
        href: index.qmd
      - text: About  
        href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

